project_id = "gsbbrkbeyxsqqjqhptrn"

[api]
enabled = true
port = 54321
schemas = ["public"]
extra_search_path = ["public"]
max_rows = 1000

[functions.conclude-card-payment]
verify_jwt = false

[functions.quitaplus-token]
verify_jwt = false

[functions.quitaplus-proxy]
verify_jwt = false

[functions.quitamais-payment-link]
verify_jwt = false

[functions.quitamais-link-search]
verify_jwt = false

[functions.process-payment]
verify_jwt = false

[functions.payment-splits]
verify_jwt = false

[functions.admin-reports]
verify_jwt = false

[functions.export-worker]
verify_jwt = false

[functions.public-payment-link]
verify_jwt = false

[functions.charge-links]
verify_jwt = true

[functions.create-user-admin]
verify_jwt = true

[db]
port = 54322
shadow_port = 54320
major_version = 15

[studio]
enabled = true
port = 54323
api_url = "http://127.0.0.1:54321"

[inbucket]
enabled = true
port = 54324
smtp_port = 54325
pop3_port = 54326

[storage]
enabled = true
port = 54327
file_size_limit = "50MiB"

[auth]
enabled = true
port = 54328
site_url = "http://127.0.0.1:3000"
additional_redirect_urls = ["https://gsbbrkbeyxsqqjqhptrn.supabase.co"]
jwt_expiry = 3600
enable_signup = true
email_double_confirm_changes = true

[auth.email]
enable_signup = true
double_confirm_changes = true
enable_confirmations = false

[functions.quitamais-auth]
verify_jwt = false

[functions.process-charge]
verify_jwt = false

[functions.recurring-charges-cron]
verify_jwt = false

[functions.send-mock-message]
verify_jwt = false

[functions.recurrences-manager]
verify_jwt = false

[functions.refunds-scheduler]
verify_jwt = false

[functions.thank-you-summary]
verify_jwt = false

[functions.company-settings]
verify_jwt = true

[functions.update-company-settings]
verify_jwt = true

[functions.subscription-manager]
verify_jwt = false

[functions.create-admin-user]
verify_jwt = false

[functions.quitaplus-prepayment]
verify_jwt = false

[functions.quitaplus-link-boleto]
verify_jwt = false

[functions.subscription-status]
verify_jwt = false

[functions.quitaplus-prepayment-test]
verify_jwt = false

[functions.quitaplus-simulation]
verify_jwt = false

[functions.abacatepay-pix-create]
verify_jwt = true

[functions.abacatepay-webhook]
verify_jwt = false

[functions.abacatepay-pix-qrcode]
verify_jwt = false