// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gsbbrkbeyxsqqjqhptrn.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImdzYmJya2JleXhzcXFqcWhwdHJuIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgyODk5NTQsImV4cCI6MjA3Mzg2NTk1NH0.I5l0SDwsAN_rsSdoZiE9GAndkn3tkqX44O5ypu0cu7w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

// Limpar qualquer sessão residual do localStorage ao carregar o SDK
// (garante que tokens de sessões anteriores não sejam reutilizados)
Object.keys(localStorage)
  .filter(k => k.startsWith('sb-'))
  .forEach(k => localStorage.removeItem(k));

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    persistSession: false,   // Sessões NUNCA são salvas no localStorage
    autoRefreshToken: true,  // Refresh funciona enquanto a aba estiver aberta
    detectSessionInUrl: true, // Necessário para magic links / reset de senha
  }
});